version: '3.8'

services:
  neohub:
    image: ghcr.io/brianhumlicek/neohub:latest
    container_name: neohub
    ports:
      - "8080:5181"
      - "8443:8181"
      - "3072:3072"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - EnableHttps=false
    volumes:
      - ./persist:/app/persist
    restart: unless-stopped